### PR TITLE
Update primos.html

### PR DESCRIPTION
**Pull request by Alisax3**

### CODE REVIEW

**Comment by JuanReneSoler** [comment]
me gusto tu codigo

**Comment by JuanReneSoler** [comment]
me gusto tu codigo

**Comment by Alisax3** [comment]
Hahahahah, gracias.. Me salvaste!!! xD :D
On Jul 15, 2016, at 8:11 PM, JuanReneSoler <notifications@github.com<mailto:notifications@github.com>> wrote:


me gusto tu codigo

**Comment by JuanReneSoler** [comment]
[😉][♥]

________________________________
De: Alisax3 <notifications@github.com>
Enviado: sábado, 16 de julio de 2016 12:12:58 a. m.
Para: JuanReneSoler/Prueba
Cc: JuanReneSoler; State change
Asunto: Re: [JuanReneSoler/Prueba] Update primos.html (#1)

Hahahahah, gracias.. Me salvaste!!! xD :D
On Jul 15, 2016, at 8:11 PM, JuanReneSoler <notifications@github.com<mailto:notifications@github.com>> wrote:


me gusto tu codigo

**Pull request merged**
